services:
  aave-monitor:
    build: .
    container_name: aave-monitor
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
    environment:
      - ACCOUNT_ADDRESS=${ACCOUNT_ADDRESS}
      - RPC_URL=${RPC_URL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - HEALTH_FACTOR_ALERT_THRESHOLD=${HEALTH_FACTOR_ALERT_THRESHOLD:-1.4}
      - NODE_ENV=production
    # Keep the container running
    tty: true
    stdin_open: true
